# Generated by Django 6.0.4 on 2026-06-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('nama_metode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metode_pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('nomor_invoice', models.CharField(max_length=50, unique=True)),
                ('total_biaya_tindakan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_biaya_obat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waktu_pembayaran', models.DateTimeField(blank=True, null=True)),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.kunjungan')),
                ('metode_bayar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.metodepembayaran')),
            ],
            options={
                'db_table': 'tagihan',
            },
        ),
    ]
