# Generated by Django 6.0.5 on 2026-05-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_loket', models.CharField(max_length=255, unique=True)),
                ('kunjungan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pelayanan.kunjungan')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'db_table': 'loket',
            },
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tiket', models.CharField(max_length=20, unique=True)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.kunjungan')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pasien')),
            ],
            options={
                'db_table': 'tiket',
            },
        ),
    ]
