# Generated by Django 6.0.4 on 2026-06-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('nama_loket', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'loket',
            },
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kode_poli', models.CharField(max_length=10, unique=True)),
                ('nama_poli', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'poli',
            },
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('no_tiket', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tiket',
            },
        ),
        migrations.CreateModel(
            name='JadwalPraktik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('hari', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dokter')),
            ],
            options={
                'db_table': 'jadwal_praktik',
            },
        ),
    ]
