# Generated by Django 6.0.4 on 2026-06-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('administrasi', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loket',
            name='kunjungan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pelayanan.kunjungan'),
        ),
        migrations.AddField(
            model_name='loket',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='jadwalpraktik',
            name='poli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrasi.poli'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='kunjungan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.kunjungan'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pasien'),
        ),
    ]
