# Generated by Django 6.0.4 on 2026-06-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kode_entity', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique code', max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('_nama_kategori', models.CharField(db_column='nama_kategori', help_text='Private field - access via @property', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategori Obat',
                'db_table': 'kategori_obat',
                'permissions': [('can_manage_kategori', 'Can manage kategori obat')],
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kode_entity', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique code', max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('nama_obat', models.CharField(db_index=True, max_length=255)),
                ('satuan', models.CharField(max_length=20)),
                ('_stok', models.PositiveIntegerField(db_column='stok', default=0, help_text='Private field - akses via @property')),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.kategoriobat')),
            ],
            options={
                'db_table': 'obat',
                'permissions': [('can_manage_stok', 'Can manage stok obat'), ('can_view_harga', 'Can view harga obat')],
                'unique_together': {('kode_entity', 'kategori')},
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kode_entity', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique code', max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('_status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], db_column='status', default='diproses', max_length=20)),
                ('tanggal_resep', models.DateTimeField(auto_now_add=True)),
                ('apoteker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.rekammedis')),
            ],
            options={
                'db_table': 'resep',
                'permissions': [('can_approve_resep', 'Can approve resep'), ('can_cancel_resep', 'Can cancel resep')],
            },
        ),
        migrations.CreateModel(
            name='DetailResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('_jumlah_diminta', models.PositiveIntegerField(db_column='jumlah_diminta', help_text='Private field - akses via @property')),
                ('dosis_aturan', models.CharField(max_length=100)),
                ('subtotal_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.obat')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.resep')),
            ],
            options={
                'db_table': 'detail_resep',
                'unique_together': {('resep', 'obat')},
            },
        ),
    ]
