# Generated by Django 6.0.5 on 2026-06-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pelayanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kategori_obat',
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('nama_obat', models.CharField(max_length=255)),
                ('kode_obat', models.CharField(max_length=10, unique=True)),
                ('satuan', models.CharField(max_length=20)),
                ('stok', models.PositiveIntegerField()),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.kategoriobat')),
            ],
            options={
                'db_table': 'obat',
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='diproses', max_length=20)),
                ('tanggal_resep', models.DateTimeField(auto_now_add=True)),
                ('apoteker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.rekammedis')),
            ],
            options={
                'db_table': 'resep',
            },
        ),
        migrations.CreateModel(
            name='DetailResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('jumlah_diminta', models.PositiveIntegerField()),
                ('dosis_aturan', models.CharField(max_length=100)),
                ('subtotal_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.obat')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmasi.resep')),
            ],
            options={
                'db_table': 'detail_resep',
            },
        ),
    ]
