# Generated by Django 6.0.5 on 2026-05-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateField()),
                ('nomor_antrean', models.PositiveIntegerField()),
                ('status', models.CharField(default='menunggu', max_length=20)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.jadwalpraktik')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pasien')),
            ],
            options={
                'db_table': 'kunjungan',
            },
        ),
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('diagnosa', models.TextField()),
                ('tekanan_darah', models.CharField(max_length=20)),
                ('suhu_tubuh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.kunjungan')),
            ],
            options={
                'db_table': 'rekam_medis',
            },
        ),
        migrations.CreateModel(
            name='TindakanRekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelayanan.rekammedis')),
                ('tindakan_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.tindakanmedis')),
            ],
            options={
                'db_table': 'tindakan_rekam_medis',
            },
        ),
    ]
