# Generated by Django 6.0.4 on 2026-05-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_metode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metode_pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_poli', models.CharField(max_length=10, unique=True)),
                ('nama_poli', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'poli',
            },
        ),
        migrations.CreateModel(
            name='TindakanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tindakan', models.CharField(blank=True, max_length=10, unique=True)),
                ('nama_tindakan', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'tindakan_medis',
            },
        ),
        migrations.CreateModel(
            name='JadwalPraktik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dokter')),
                ('poli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.poli')),
            ],
            options={
                'db_table': 'jadwal_praktik',
            },
        ),
    ]
